# ===== Generated by unix-on-windows =====
# Regenerate: run setup.ps1 again

# Encoding (AI/agent friendly)
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
[Console]::InputEncoding = [System.Text.Encoding]::UTF8
$OutputEncoding = [System.Text.Encoding]::UTF8
$env:LANG = 'C.UTF-8'

# PSReadLine (predictive IntelliSense)
if ($host.Name -eq 'ConsoleHost') {
    try {
        Set-PSReadLineOption -PredictionSource History -ErrorAction Stop
        Set-PSReadLineOption -PredictionViewStyle ListView -ErrorAction Stop
        Set-PSReadLineOption -EditMode Windows
        Set-PSReadLineOption -BellStyle None
        Set-PSReadLineOption -HistorySearchCursorMovesToEnd
        Set-PSReadLineKeyHandler -Key Tab -Function MenuComplete
        Set-PSReadLineKeyHandler -Key UpArrow -Function HistorySearchBackward
        Set-PSReadLineKeyHandler -Key DownArrow -Function HistorySearchForward
        Set-PSReadLineOption -Colors @{ InlinePrediction = '#5A5A5A' }
    } catch { }
}

# eza aliases
if (Get-Command eza -ErrorAction SilentlyContinue) {
    function ls { eza --icons --group-directories-first @args }
    function ll { eza -la --icons --group-directories-first --git @args }
    function lt { eza -la --icons --tree --level=2 @args }
}

# Proxy Helpers
function proxy-on {
    $env:HTTP_PROXY = '{{PROXY_URL}}'
    $env:HTTPS_PROXY = '{{PROXY_URL}}'
    $env:NO_PROXY = 'localhost,127.0.0.1,::1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16'
    Write-Host 'Proxy ON ({{PROXY_URL}})' -ForegroundColor Green
}
function proxy-off {
    Remove-Item Env:HTTP_PROXY -ErrorAction SilentlyContinue
    Remove-Item Env:HTTPS_PROXY -ErrorAction SilentlyContinue
    Remove-Item Env:NO_PROXY -ErrorAction SilentlyContinue
    Write-Host 'Proxy OFF' -ForegroundColor Yellow
}
function git-proxy {
    git config --global http.proxy '{{PROXY_URL}}'
    git config --global https.proxy '{{PROXY_URL}}'
    Write-Host 'Git proxy enabled' -ForegroundColor Green
}
function git-noproxy {
    git config --global --unset http.proxy
    git config --global --unset https.proxy
    Write-Host 'Git proxy disabled' -ForegroundColor Yellow
}

# General Helpers
function which($name) { (Get-Command $name -ErrorAction SilentlyContinue).Source }
function mkcd($dir) { New-Item -ItemType Directory -Path $dir -Force | Out-Null; Set-Location $dir }

# Unix Bridge (MSYS2 tools from PowerShell)
$msys2Bin = "$env:USERPROFILE\scoop\apps\msys2\current\usr\bin"
if (Test-Path "$msys2Bin\bash.exe") {
    function bash { & "$msys2Bin\bash.exe" --login @args }
}
$gitBashBin = "$env:USERPROFILE\scoop\apps\git\current\bin"
if (Test-Path "$gitBashBin\bash.exe") {
    function gbash { & "$gitBashBin\bash.exe" --login -i @args }
}

# zoxide (smart cd)
if (Get-Command zoxide -ErrorAction SilentlyContinue) {
    Invoke-Expression (&zoxide init powershell | Out-String)
}

# Starship Prompt (interactive only)
if ([Environment]::UserInteractive -and (Get-Command starship -ErrorAction SilentlyContinue)) {
    Invoke-Expression (&starship init powershell | Out-String)
}


